# Generated by Django 4.1.3 on 2023-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('otp', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
