# Generated by Django 4.1.3 on 2023-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_permission_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='role_id',
        ),
        migrations.AddField(
            model_name='permission',
            name='role_id',
            field=models.ManyToManyField(to='account.role'),
        ),
    ]
