# Generated by Django 4.1.3 on 2023-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_permission_role_id_permission_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role_id',
            field=models.ManyToManyField(related_name='rolePermission', to='account.role'),
        ),
    ]
