# Generated by Django 4.1.3 on 2023-03-17 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_alter_chartdetails_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdetails',
            name='modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 17, 10, 57, 4, 391898, tzinfo=datetime.timezone.utc)),
        ),
    ]
