# Generated by Django 4.1.3 on 2023-03-18 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_alter_chartdetails_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdetails',
            name='modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 18, 12, 14, 28, 768334)),
        ),
    ]
