# Generated by Django 4.1.3 on 2023-03-21 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_alter_chartdetails_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdetails',
            name='modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 21, 23, 1, 37, 163050)),
        ),
    ]
